smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
#max nb of iterations the algorithm will attemp smooting the path
      max_its: 1000
#enable the plugin to recursively smooth the path to refine the quality even further
      do_refinement: true